# Generated by Django 4.2.18 on 2025-01-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('refresh_token', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=100)),
                ('expire_date_token', models.DateTimeField()),
            ],
        ),
    ]
