# Generated by Django 4.2.18 on 2025-01-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravapp', '0005_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='elapsed_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='moving_time',
            field=models.BigIntegerField(),
        ),
    ]
